project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "General Guidance"
        href: sample.qmd
      - text: "Exercises"
        menu:
          - text: "Alcohol Exercise"
            href: alcohol-exercise/intro.qmd
          - text: "Anscombe's Quartet"
            href: anscombes-quartet/intro.qmd
  title: "Reproducibility Exercises"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    contents:
    
            ###########
          # ALCOHOL #
          ###########

      - section: "[Alcohol Exercise]{.underline}"
        contents:
        - section: "**Setup**"
          contents:
            - alcohol-exercise/intro.qmd
            - alcohol-exercise/folders.qmd
            - alcohol-exercise/dataset-and-codebook.qmd
        - section: "**Writing the do files**"
          contents:
            - alcohol-exercise/dofiles.qmd
            - alcohol-exercise/processing-do.qmd
            - alcohol-exercise/data-appendix-do.qmd
            - alcohol-exercise/analysis-do.qmd
        - section: "**The README file**"
          contents:
            - alcohol-exercise/readme.qmd
        - section: "**The printed report**"
          contents:
            - alcohol-exercise/report.qmd
            - alcohol-exercise/report-appendix.qmd
            - alcohol-exercise/report-figures.qmd
        - section: "**Electronic documentation**"
          contents: 
            - alcohol-exercise/e-doc.qmd

        - text: "---"
            ############
            # ANSCOMBE #
            ############

      - section: "[Anscombe's Quartet]{.underline}"
        contents: 
        - section: "**Setup**"
          contents:
            - anscombes-quartet/intro.qmd
            - anscombes-quartet/setup.qmd
        - section: "**Writing text and code**"
          contents:
            - anscombes-quartet/text-and-code-overview.qmd
            - anscombes-quartet/text-and-code-questions.qmd
        - section: "**Finishing up**"
          contents:
            - anscombes-quartet/compendium.qmd

format:
  html:
    grid:
      sidebar-width: 350px
    theme: cosmo
    css: styles.css
    toc: true
