project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Quarto Testing"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Setup"
        contents:
          - Intro.qmd
          - Folders.qmd
          - Dataset and Codebook.qmd
      - section: "Writing the do files"
        contents:
          - dofiles.qmd
          - processing-do.qmd
          - data-appendix-do.qmd
    
format:
  html:
    grid:
      sidebar-width: 350px
    theme: cosmo
    css: styles.css
    toc: true



