project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Alcohol Project"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Setup"
        contents:
          - Intro.qmd
          - Folders.qmd
          - Dataset and Codebook.qmd
      - section: "Writing the do files"
        contents:
          - dofiles.qmd
          - processing-do.qmd
          - data-appendix-do.qmd
          - analysis-do.qmd
      - section: "The README File"
        contents:
          - readme.qmd
      - section: "The printed report"
        contents:
          - report.qmd
          - report-appendix.qmd
          - report-figures.qmd
      - section: "Electronic Documentation"
        contents: 
          - e-doc.qmd
format:
  html:
    grid:
      sidebar-width: 350px
    theme: cosmo
    css: styles.css
    toc: true



