project:
  type: website
  output-dir: docs

website:
  title: "Fresh Quarto Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - Quantitative Variables in Finite Populations and Samples.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



